/stereo_down:
  left:
    trigger_mode: "fixedrate"
    trig_rate: 10
    auto_exposure: True
    exposure: 0.002
    auto_gain: True
    gain: 0
    auto_whitebalance: True
    whitebalance_red: 100
    whitebalance_blue: 100
    binning_x: 1
    binning_y: 1
    decimation_x: 2
    decimation_y: 2
    x_offset: 8
    y_offset: 8
    width: 1920
    height: 1440
    frame_id: "/stereo_down/left_optical"
    trig_timestamp_topic: "trigger"
    auto_adjust_stream_bytes_per_second: False
    stream_bytes_per_second: 115000000
    exposure_auto_max: 0.006
    exposure_auto_target: 40
    gain_auto_max: 20
    gain_auto_target: 40
    pixel_format: "Bayer8"
  right:
    trigger_mode: "syncin1"
    trig_rate: 10
    auto_exposure: True
    exposure: 0.002
    auto_gain: True
    gain: 0
    auto_whitebalance: True
    whitebalance_red: 100
    whitebalance_blue: 100
    binning_x: 1
    binning_y: 1
    decimation_x: 2
    decimation_y: 2
    x_offset: 8
    y_offset: 8
    width: 1920
    height: 1440
    frame_id: "/stereo_down/right_optical"
    trig_timestamp_topic: "trigger"
    auto_adjust_stream_bytes_per_second: False
    stream_bytes_per_second: 115000000
    exposure_auto_max: 0.006
    exposure_auto_target: 40
    gain_auto_max: 20
    gain_auto_target: 40
    pixel_format: "Bayer8"